name: Test GH Action

on:
  push:
    branches:
      - main

# env: 
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run 
        uses: PTPhongKMF/test-gh-action@main
        with:
          name: test hehe